services:
  swagger-users:
    image: swaggerapi/swagger-ui:latest
    ports:
      - "8081:8080"
    environment:
      SWAGGER_JSON: /openapi/users.swagger.yaml
    volumes:
      - ./docs/openapi/swagger:/openapi:ro

  swagger-transactions:
    image: swaggerapi/swagger-ui:latest
    ports:
      - "8082:8080"
    environment:
      SWAGGER_JSON: /openapi/transactions.swagger.yaml
    volumes:
      - ./docs/openapi/swagger:/openapi:ro
