services:
  swagger-users:
    image: swaggerapi/swagger-ui:latest
    ports:
      - "8081:8080"
    environment:
      SWAGGER_JSON: /openapi/ms-users.yaml
    volumes:
      - ./docs/openapi:/openapi:ro

  swagger-transactions:
    image: swaggerapi/swagger-ui:latest
    ports:
      - "8082:8080"
    environment:
      SWAGGER_JSON: /openapi/ms-transactions.yaml
    volumes:
      - ./docs/openapi:/openapi:ro
